title: "Medium Blog"
description: "A Jekyll-powered, math-enabled blog for medium-style posts"
baseurl: "" # or "/repo-name" if using a project site
url: ""     # GitHub Pages will fill this in

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"

# Keep it simple for now—add features later!
