title: "Medium Blog"
description: "A Jekyll-powered, math-enabled blog for medium-style posts"
baseurl: "/Medium_post"               # must start with a slash, no trailing slash
url: "https://dino65-dev.github.io"   # no trailing slash
permalink: pretty

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"

# Keep it simple for now—add features later!
